### ISSUE TITLE
Leaving Applait

### ISSUE THREAD

**Issue by kaustavdm** [applait/meta#27]
To @debloper and @TheSigyn,

Please consider this as my and @pawzoned's formal notice for resigning from our roles and responsibilities in @applait.

I have given this initiative long enough time and effort. I have arrived at a juncture where I am convinced that while our ideologies may overlap, our focus, approach and execution strategies do not. I am not in agreement with the direction, speed, effort and intent in the execution of the plans at Applait.

I'm sure we will make a great team working on FOSS projects or in open web communities, but I don't see us building a sustainable business. I have waited long to write this but it is finally time that I move on to things where I can make more use of my skills and ideas.

This is not an easy decision for us and I have personally deliberated over this for over a year, and, now I am confident about my call. I don't want to drag this any further than now. This decision is non-negotiable.

My interest lies in communications, language and connectivity and I will likely pursue endeavours in those directions. We have learnt a lot, discussed a lot and had a lot of good time. I am honoured and humbled to have those conversations and those long hours of braingasms. This separation is also to ensure that we continue doing that without a business interest getting in the way of our friendship.

## Transfer of Credentials

- Currently, some of the credentials in different services have my name and email. I'll note them down in a shared document so that they can be either reused in future or changed to something else.
- I also have a few places, including Github, where my credit cards are charged monthly. I will remove them and you will have to put in yours instead.
- I have the domains of xplex registered under my personal account. I'll need you to give me a registrar to transfer the domains to.

## Transfer of Rights

I also want to ensure that intellectual property rights of upspeak can be safely transferred out of Applait, with Applait claiming no stake in it in future. At present, I own the domains personally, and I drafted the core ideas that form upspeak today. But realizing that it spun off from our early discussions on ConQ, which was a very different product than what upspeak is. I want to make this a clear question, so that I may work on it separately with other people and take different directions with it. If you do not agree to the transfer, let me know and I will not reuse the branding and code behind what we have in upspeak.

Everything else that we have done for Applait stays with Applait. There are many prototypes and experiments that have value going ahead should the team decide to invest in them.

We would be more than happy to transfer our stakes in Applait back to the company.

## Legal process to follow

Please consider this as our letter of resignation effective immediately. We need to follow a process to strike my and Nayanika's name off the list of partners for Applait and file it with the required authorities. Please begin the process as soon as possible so that both of us are removed from the list of partners.

**Comment by debloper** [comment]
Closing this.

## Updates:
- Made all the repos public. Will have to run some chores for proper archival. Will convert to GitHub's **Teams for Open Source** (free tier org) right after posting this message.
- Almost all procedures are done for Applait's closure (closing bank accounts, applications & signatures etc. by Q3 2018), except for the LLP closure itself. @TheSigyn isn't too keen on completing that for some reason, and I've already expressed (well before the starting of 2019-20 fiscal year) that I won't be taking any responsibility for the risks involved in delaying the process anymore.
- Couldn't transfer upspeak directly to @kaustavdm as github wouldn't allow transferring repo to non-members. So, had to hop it through my personal account (pending his approval/acceptance). Should've done earlier, but was waiting on a confirmation to my question on this.

*Live long and prosper.*
